services:
  animal-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: animal-go-prod
    runtime: nvidia
    ports:
      - "3000:3000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    volumes:
      - ./nets:/app/nets:ro
      - ./logs:/app/logs
